name: Build
on: [push, pull_request]

jobs:

  build-freebsd:
    name: Build FreeBSD
    runs-on: macos-11
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build FreeBSD
      id: build-freebsd
      uses: vmactions/freebsd-vm@v0.3.0
      with:
        usesh: true
        mem: 4096
        prepare: pkg install -y git cmake pkgconf gettext-tools boost-libs glib gnutls qt6-base qt6-tools sqlite gstreamer1 gstreamer1-plugins chromaprint protobuf protobuf-c taglib libcdio libmtp gdk-pixbuf2 libgpod fftw3 googletest iconv icu
        run: echo TEST


  build-macos-homebrew:
    name: Build macOS Homebrew
    runs-on: macos-11
    steps:

      - name: Remove packages
        run: brew remove aliyun-cli ant aws-sam-cli azure-cli bazelisk bicep composer geckodriver ghostscript helm httpd imagemagick kotlin maven mongodb-community@5.0 mongodb-database-tools mongosh nginx php postgresql@14 ruby@2.7 rustup-init sbt selenium-server swiftformat switchaudio-osx chromedriver firefox google-chrome julia microsoft-edge r session-manager-plugin

      - name: Update packages
        run: brew update

      - name: Upgrade packages
        run: brew upgrade || true


  build-macos-macports:
    name: Build macOS Macports
    runs-on: macos-11
    steps:
      - name: Install macports
        run: |
          wget https://github.com/macports/macports-base/releases/download/v2.7.1/MacPorts-2.7.1-10.15-Catalina.pkg
          sudo installer -pkg ./MacPorts-2.7.1-10.15-Catalina.pkg -target /
